version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
#    image: muhmdarif/laravel-project-app:latest
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
      - ./.env:/var/www/html/.env
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    depends_on:
      - db
    command: >
      sh -c "
      composer install &&
      php artisan key:generate &&
      php artisan storage:link &&
      chmod -R 775 /var/www/html/storage /var/www/html/bootstrap/cache &&
      chown -R www-data:www-data /var/www/html &&
      php artisan migrate --force &&
      php-fpm
      "
  webserver:
    image: nginx:latest
    container_name: laravel_webserver
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: laravel_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

